#!/usr/bin/env python3
"""
Generate SQL seed file from Excel waybill data
Extracts: Drivers, Customers, Deliveries, Waybills, Waybill Items
"""

import pandas as pd
import json
import sys
import re
from datetime import datetime
from collections import defaultdict

# Excel file path
EXCEL_FILE = 'waybill_excel/Waybills_31-10-2025.xlsx'
OUTPUT_FILE = 'assets/waybill_seed.sql'

# Table prefixes (will be replaced with actual prefix in SQL)
# Note: This will be used as {PREFIX}kit_tablename, so use just 'wp_' if your prefix is 'wp_kit_'
PREFIX = 'wp_'

def clean_string(value):
    """Clean string values, handle NaN and None"""
    if pd.isna(value) or value is None:
        return None
    return str(value).strip() if str(value).strip() else None

def clean_decimal(value):
    """Clean decimal values"""
    if pd.isna(value) or value is None:
        return 0.0
    if isinstance(value, str):
        # Remove non-numeric characters except decimal point
        cleaned = re.sub(r'[^0-9.]', '', value)
        return float(cleaned) if cleaned else 0.0
    return float(value)

def clean_int(value):
    """Clean integer values"""
    if pd.isna(value) or value is None:
        return 0
    if isinstance(value, str):
        cleaned = re.sub(r'[^0-9]', '', value)
        return int(cleaned) if cleaned else 0
    return int(value)

def escape_sql(value):
    """Escape SQL string values"""
    if value is None:
        return 'NULL'
    # Replace single quotes with doubled quotes
    return "'" + str(value).replace("'", "''") + "'"

def format_datetime(value):
    """Format datetime for SQL"""
    if pd.isna(value) or value is None:
        return 'CURRENT_TIMESTAMP'
    if isinstance(value, pd.Timestamp):
        return f"'{value.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(value, str):
        # Try to parse the string
        try:
            dt = pd.to_datetime(value)
            return f"'{dt.strftime('%Y-%m-%d %H:%M:%S')}'"
        except:
            return 'CURRENT_TIMESTAMP'
    return 'CURRENT_TIMESTAMP'

def format_date(value):
    """Format date for SQL"""
    if pd.isna(value) or value is None:
        return 'NULL'
    if isinstance(value, pd.Timestamp):
        return f"'{value.strftime('%Y-%m-%d')}'"
    if isinstance(value, str):
        try:
            dt = pd.to_datetime(value)
            return f"'{dt.strftime('%Y-%m-%d')}'"
        except:
            return 'NULL'
    return 'NULL'

def parse_customer_name(customer_name):
    """Parse customer name into first name and surname"""
    if not customer_name or pd.isna(customer_name):
        return ('Unknown', 'Customer')
    
    parts = str(customer_name).strip().split(' ', 1)
    first_name = parts[0] if parts else 'Unknown'
    surname = parts[1] if len(parts) > 1 else 'Customer'
    return (first_name, surname)

def get_city_country_mapping():
    """
    Return mapping of city names to (city_id, country_id)
    Loads from exported city_mapping.json file (generated by export_city_mapping.php)
    Falls back to hardcoded mapping if file doesn't exist
    """
    import os
    
    # Try to load from exported JSON file first
    mapping_file = os.path.join(os.path.dirname(__file__), 'assets', 'city_mapping.json')
    if os.path.exists(mapping_file):
        try:
            with open(mapping_file, 'r', encoding='utf-8') as f:
                raw_mapping = json.load(f)
                # Convert to simplified format: city_name -> (city_id, country_id)
                mapping = {}
                for key, value in raw_mapping.items():
                    if isinstance(value, dict):
                        mapping[key] = (value['city_id'], value['country_id'])
                print(f"Loaded {len(mapping)} city mappings from {mapping_file}")
                return mapping
        except Exception as e:
            print(f"Warning: Failed to load city mapping from {mapping_file}: {e}")
            print("Falling back to hardcoded mapping...")
    
    # Fallback: hardcoded mapping (should not be needed if export script works)
    mapping = {}
    print("Warning: Using hardcoded city mapping. Run export_city_mapping.php for accurate IDs.")
    # South Africa (country_id likely 1)
    za_cities = ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth']
    for idx, city in enumerate(za_cities, start=1):
        mapping[city] = (idx, 1)
    
    # Tanzania (country_id likely 2)
    tz_cities = ['Dar es Salaam', 'Dodoma', 'Arusha', 'Mbeya', 'Mwanza', 'Iringa', 
                 'Kilombero', 'Mafinga', 'Makambako', 'Mfundi', 'Mikumi', 'Morogoro', 
                 'Moshi', 'Sao Hill', 'Sumbawanga', 'Tanga', 'Zanzibar', 'Gombe Kinshasa']
    start_id = len(za_cities) + 1
    for idx, city in enumerate(tz_cities, start=start_id):
        mapping[city] = (idx, 2)
    
    return mapping

def get_direction_id(origin_country_id, destination_country_id, city_map):
    """
    Determine direction_id from origin and destination countries
    direction_id 1: South Africa -> South Africa (warehouse)
    direction_id 2: South Africa -> Tanzania
    direction_id 3: Tanzania -> South Africa
    """
    # Load direction mapping from database or use defaults
    # Default mapping based on known structure:
    # SA (country_id=1) -> SA (country_id=1) = direction_id 1 (warehouse)
    # SA (country_id=1) -> TZ (country_id=2) = direction_id 2
    # TZ (country_id=2) -> SA (country_id=1) = direction_id 3
    
    if origin_country_id == 1 and destination_country_id == 1:
        return 1  # Warehouse (SA -> SA)
    elif origin_country_id == 1 and destination_country_id == 2:
        return 2  # SA -> TZ
    elif origin_country_id == 2 and destination_country_id == 1:
        return 3  # TZ -> SA
    else:
        # Default to SA -> TZ (direction_id 2) for unknown combinations
        return 2

def get_origin_country_from_city(city_name, city_map):
    """Determine origin country - default to South Africa (1) for most shipments"""
    # Most shipments originate from South Africa
    # Only use Tanzania as origin if explicitly indicated
    # For now, default to SA (country_id = 1)
    return 1

def main():
    print("Reading Excel file...")
    
    try:
        # Read Excel file
        df = pd.read_excel(EXCEL_FILE, sheet_name='waybills')
        
        # Convert datetime columns
        for col in df.columns:
            if df[col].dtype == 'datetime64[ns]':
                df[col] = df[col].astype(str)
        
        # Replace NaN with None for easier handling
        df = df.replace({pd.NA: None, pd.NaT: None})
        
        print(f"Loaded {len(df)} rows from Excel")
        
        # Data structures
        drivers_map = {}  # driver_name -> driver_id
        customers_map = {}  # (name, surname) -> cust_id
        deliveries_map = {}  # (driver_name, dispatch_date) -> delivery_id
        waybills_map = {}  # waybill_no -> waybill_data
        
        # Counters for IDs
        driver_counter = 1
        customer_counter = 1000  # Start from 1000 for cust_id
        delivery_counter = 1
        waybill_counter = 1
        
        # City mapping
        city_map = get_city_country_mapping()
        
        # Collect unique drivers
        unique_drivers = set()
        for driver in df['Driver'].dropna():
            unique_drivers.add(str(driver).strip())
        
        print(f"Found {len(unique_drivers)} unique drivers")
        
        # Collect unique customers
        unique_customers = {}
        for _, row in df.iterrows():
            customer_name = clean_string(row.get('Customer'))
            if customer_name:
                first_name, surname = parse_customer_name(customer_name)
                key = (first_name, surname)
                if key not in unique_customers:
                    unique_customers[key] = {
                        'name': first_name,
                        'surname': surname,
                        'cell': clean_string(row.get('Cell')),
                        'company': clean_string(row.get('Company')) or 'Individual',
                        'address': clean_string(row.get('Address')),
                        'city': clean_string(row.get('City')),
                    }
        
        print(f"Found {len(unique_customers)} unique customers")
        
        # Group rows by driver + dispatch date (delivery groups)
        delivery_groups = defaultdict(list)
        for _, row in df.iterrows():
            driver = clean_string(row.get('Driver'))
            dispatch_date = clean_string(row.get('Truck Dispatch Date'))
            if driver and dispatch_date:
                key = (driver, dispatch_date)
                delivery_groups[key].append(row)
        
        print(f"Found {len(delivery_groups)} delivery groups")
        
        # Generate SQL
        sql_statements = []
        sql_statements.append("-- Waybill Seed Data Generated from Excel")
        sql_statements.append(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        sql_statements.append(f"-- Table prefix used: {PREFIX}kit_\n")
        sql_statements.append("-- If your WordPress table prefix is different, replace 'wp_' with your actual prefix\n")
        
        sql_statements.append("SET FOREIGN_KEY_CHECKS=0;\n")
        
        # 1. INSERT Drivers
        sql_statements.append("-- ============================================")
        sql_statements.append("-- DRIVERS")
        sql_statements.append("-- ============================================\n")
        
        for driver_name in sorted(unique_drivers):
            drivers_map[driver_name] = driver_counter
            sql_statements.append(
                f"INSERT INTO {PREFIX}kit_drivers "
                f"(id, name, phone, email, license_number, is_active, created_at, updated_at) VALUES "
                f"({driver_counter}, {escape_sql(driver_name)}, NULL, NULL, NULL, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);"
            )
            driver_counter += 1
        
        sql_statements.append("")
        
        # 2. INSERT Customers
        sql_statements.append("-- ============================================")
        sql_statements.append("-- CUSTOMERS")
        sql_statements.append("-- ============================================\n")
        
        for (first_name, surname), customer_data in unique_customers.items():
            cust_id = customer_counter
            customers_map[(first_name, surname)] = cust_id
            
            city_name = customer_data['city']
            city_id = '9'  # Default to city_id 9
            country_id = '2'  # Default to Tanzania (country_id 2)
            
            if city_name:
                city_name_clean = str(city_name).strip()
                # Try exact match first
                if city_name_clean in city_map:
                    resolved_city_id = city_map[city_name_clean][0]
                    resolved_country_id = city_map[city_name_clean][1]
                    city_id = str(resolved_city_id)
                    country_id = str(resolved_country_id)
                else:
                    # Try case-insensitive match
                    city_name_lower = city_name_clean.lower()
                    if city_name_lower in city_map:
                        resolved_city_id = city_map[city_name_lower][0]
                        resolved_country_id = city_map[city_name_lower][1]
                        city_id = str(resolved_city_id)
                        country_id = str(resolved_country_id)
                    else:
                        # Try matching with normalized spacing/capitalization
                        # Find closest match by checking if any key contains the city name or vice versa
                        for key, value in city_map.items():
                            if isinstance(value, tuple):
                                key_clean = str(key).strip()
                                if (city_name_clean.lower() == key_clean.lower() or
                                    city_name_clean.replace(' ', '').lower() == key_clean.replace(' ', '').lower()):
                                    resolved_city_id = value[0]
                                    resolved_country_id = value[1]
                                    city_id = str(resolved_city_id)
                                    country_id = str(resolved_country_id)
                                    break
            
            # Store the resolved city_id in customer_data so we can use it for waybills
            # Default to city_id 9 if no city found
            if city_id == 'NULL':
                city_id = '9'
                country_id = '2'  # Assuming Tanzania (city_id 9 is likely Tanzania)
            customer_data['resolved_city_id'] = city_id
            customer_data['resolved_country_id'] = country_id
            
            # Ensure city_id and country_id are never NULL
            if city_id == 'NULL' or not city_id:
                city_id = '9'
            if country_id == 'NULL' or not country_id:
                country_id = '2'
            
            cell = escape_sql(customer_data['cell']) if customer_data['cell'] else 'NULL'
            company = escape_sql(customer_data['company']) if customer_data['company'] else "'Individual'"
            address = escape_sql(customer_data['address']) if customer_data['address'] else 'NULL'
            
            sql_statements.append(
                f"INSERT INTO {PREFIX}kit_customers "
                f"(id, cust_id, name, surname, cell, telephone, email_address, country_id, city_id, vat_number, address, company_name, created_at) VALUES "
                f"(NULL, {cust_id}, {escape_sql(first_name)}, {escape_sql(surname)}, {cell}, NULL, NULL, {country_id}, {city_id}, NULL, {address}, {company}, CURRENT_TIMESTAMP);"
            )
            customer_counter += 1
        
        sql_statements.append("")
        
        # 3. INSERT Deliveries
        sql_statements.append("-- ============================================")
        sql_statements.append("-- DELIVERIES")
        sql_statements.append("-- ============================================\n")
        
        for (driver_name, dispatch_date), rows in sorted(delivery_groups.items()):
            driver_id = drivers_map[driver_name]
            deliveries_map[(driver_name, dispatch_date)] = delivery_counter
            
            # Determine destination country from first waybill's city in this delivery group
            destination_country_id = 2  # Default to Tanzania
            destination_city_id = 9  # Default to Mbeya
            
            # Get destination from first row's city
            if rows and len(rows) > 0:
                first_row = rows[0]
                city_name = clean_string(first_row.get('City'))
                if city_name:
                    city_name_clean = str(city_name).strip()
                    if city_name_clean in city_map:
                        destination_city_id = city_map[city_name_clean][0]
                        destination_country_id = city_map[city_name_clean][1]
                    else:
                        city_name_lower = city_name_clean.lower()
                        if city_name_lower in city_map:
                            destination_city_id = city_map[city_name_lower][0]
                            destination_country_id = city_map[city_name_lower][1]
            
            # Origin is typically South Africa (country_id = 1)
            origin_country_id = 1
            direction_id = get_direction_id(origin_country_id, destination_country_id, city_map)
            
            # Generate delivery reference
            delivery_ref = f"DEL-{delivery_counter:04d}"
            
            sql_statements.append(
                f"INSERT INTO {PREFIX}kit_deliveries "
                f"(id, delivery_reference, direction_id, destination_city_id, dispatch_date, truck_number, driver_id, status, created_by, created_at) VALUES "
                f"({delivery_counter}, {escape_sql(delivery_ref)}, {direction_id}, {destination_city_id}, {format_date(dispatch_date)}, NULL, {driver_id}, 'scheduled', 1, CURRENT_TIMESTAMP);"
            )
            delivery_counter += 1
        
        sql_statements.append("")
        
        # 4. INSERT Waybills
        sql_statements.append("-- ============================================")
        sql_statements.append("-- WAYBILLS")
        sql_statements.append("-- ============================================\n")
        
        waybill_no_counter = 1000  # Start waybill numbers from 1000
        
        for (driver_name, dispatch_date), rows in sorted(delivery_groups.items()):
            delivery_id = deliveries_map[(driver_name, dispatch_date)]
            
            # Each row in the group is a separate waybill
            for row_idx, row in enumerate(rows):
                # Get customer
                customer_name = clean_string(row.get('Customer'))
                if not customer_name:
                    continue
                
                first_name, surname = parse_customer_name(customer_name)
                customer_id = customers_map.get((first_name, surname))
                if not customer_id:
                    continue
                
                # Extract waybill number from description if available
                waybill_description = clean_string(row.get('Waybill  description')) or ''
                waybill_no = None
                
                # Try to extract WB-XXXX pattern
                wb_match = re.search(r'WB-?\s*(\d+)', waybill_description, re.IGNORECASE)
                if wb_match:
                    waybill_no = int(wb_match.group(1))
                    # Check if already used
                    if waybill_no in waybills_map:
                        waybill_no = None  # Generate new one
                
                if not waybill_no:
                    # Generate unique waybill number
                    while waybill_no_counter in waybills_map:
                        waybill_no_counter += 1
                    waybill_no = waybill_no_counter
                    waybill_no_counter += 1
                
                waybills_map[waybill_no] = True
                
                # Extract waybill data
                item_description = clean_string(row.get('Item description')) or 'Unspecified Item'
                quantity = clean_int(row.get('QUANTITY'))
                basis = clean_string(row.get('BASIS')) or 'MASS'
                total_mass = clean_decimal(row.get('T MASS'))
                length = clean_decimal(row.get('LENGTH'))
                width = clean_decimal(row.get('WIDTH'))
                height = clean_decimal(row.get('HEIGHT'))
                total_volume = clean_decimal(row.get('T VOLUME'))
                mass_cost = clean_decimal(row.get('MASS COST'))
                vol_cost = clean_decimal(row.get('VOL COST'))
                sad500 = 1 if clean_string(row.get('SAD500')) else 0
                sadc = 1 if clean_string(row.get('SADC')) else 0
                vat = 1 if clean_string(row.get('VAT')) else 0
                supplier = clean_string(row.get('Supplier'))
                invoice_number = clean_string(row.get('CL INV #'))
                client_invoice = clean_decimal(row.get('CLIENT INVOICE ( R)'))
                waybill_creation_date = row.get('Waybill Creation Date')
                
                # Determine charge basis and total
                charge_basis = 'volume' if (basis.upper() == 'VOLUME' or (total_volume > 0 and vol_cost > mass_cost)) else 'mass'
                waybill_total = max(mass_cost, vol_cost)
                
                # Get city_id from Excel row City column - match against kit_operating_cities
                city_id = '9'  # Default to city_id 9 if no match found
                city_name = clean_string(row.get('City'))
                
                if city_name:
                    city_name_clean = str(city_name).strip()
                    # Try exact match first
                    if city_name_clean in city_map:
                        city_id = str(city_map[city_name_clean][0])
                    else:
                        # Try case-insensitive match
                        city_name_lower = city_name_clean.lower()
                        if city_name_lower in city_map:
                            city_id = str(city_map[city_name_lower][0])
                        else:
                            # Try normalized matching (handle variations like "Dar Es Salaam" vs "Dar es Salaam")
                            for key, value in city_map.items():
                                if isinstance(value, tuple):
                                    key_clean = str(key).strip()
                                    if (city_name_clean.lower() == key_clean.lower() or
                                        city_name_clean.replace(' ', '').lower() == key_clean.replace(' ', '').lower()):
                                        city_id = str(value[0])
                                        break
                
                # Ensure city_id is never NULL - always use a valid integer
                if city_id == 'NULL' or not city_id or city_id == '':
                    city_id = '9'
                
                # Determine direction_id from destination city's country
                destination_country_id = 2  # Default to Tanzania
                if city_name:
                    city_name_clean = str(city_name).strip()
                    if city_name_clean in city_map:
                        destination_country_id = city_map[city_name_clean][1]
                    else:
                        city_name_lower = city_name_clean.lower()
                        if city_name_lower in city_map:
                            destination_country_id = city_map[city_name_lower][1]
                
                # Origin is typically South Africa (country_id = 1)
                origin_country_id = 1
                direction_id = get_direction_id(origin_country_id, destination_country_id, city_map)
                
                # Prepare miscellaneous data
                misc_data = {
                    'supplier': supplier or '',
                    'client_invoice': client_invoice,
                    'invoice_number': invoice_number or ''
                }
                misc_json = json.dumps(misc_data).replace("'", "''")
                
                # Generate tracking number
                import random
                import string
                tracking_number = 'TRK-' + ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
                
                # Generate product invoice number if not provided
                if not invoice_number:
                    invoice_number = f"INV-{datetime.now().strftime('%Y%m%d')}-{waybill_no}"
                
                # INSERT Waybill (city_id is included in column list and values)
                sql_statements.append(
                    f"INSERT INTO {PREFIX}kit_waybills "
                    f"(direction_id, city_id, delivery_id, customer_id, approval, approval_userid, waybill_no, "
                    f"product_invoice_number, product_invoice_amount, waybill_items_total, item_length, item_width, "
                    f"item_height, total_mass_kg, total_volume, mass_charge, volume_charge, charge_basis, vat_include, "
                    f"warehouse, miscellaneous, include_sad500, include_sadc, return_load, tracking_number, "
                    f"created_by, last_updated_by, status, status_userid, created_at, last_updated_at) VALUES "
                    f"({direction_id}, {city_id}, {delivery_id}, {customer_id}, 'pending', NULL, {waybill_no}, "
                    f"{escape_sql(invoice_number)}, {client_invoice}, {waybill_total}, {length}, {width}, "
                    f"{height}, {total_mass}, {total_volume}, {mass_cost}, {vol_cost}, {escape_sql(charge_basis)}, "
                    f"{vat}, 0, {escape_sql(misc_json)}, {sad500}, {sadc}, 0, {escape_sql(tracking_number)}, "
                    f"1, 1, 'pending', 0, {format_datetime(waybill_creation_date)}, CURRENT_TIMESTAMP);"
                )
                
                # Note: Waybill items are not inserted - data is stored in waybill_items_total field
        
        sql_statements.append("")
        sql_statements.append("SET FOREIGN_KEY_CHECKS=1;")
        
        # Write to file
        output_sql = '\n'.join(sql_statements)
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(output_sql)
        
        print(f"\n✓ SQL seed file generated: {OUTPUT_FILE}")
        print(f"  - Drivers: {len(drivers_map)}")
        print(f"  - Customers: {len(customers_map)}")
        print(f"  - Deliveries: {len(deliveries_map)}")
        print(f"  - Waybills: {len(waybills_map)}")
        print(f"\n⚠ Note: Replace '{PREFIX}kit_' with your actual WordPress table prefix if different.")
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == '__main__':
    main()

